# Generated by Django 5.1.6 on 2025-06-22 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='historiasclinicas',
            constraint=models.UniqueConstraint(fields=('numero_historia',), name='unique_numero_historia'),
        ),
    ]
