# Generated by Django 5.1.6 on 2025-06-05 15:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='autorizaciones',
            name='padre',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.informacionpadres'),
        ),
        migrations.AlterField(
            model_name='genetistas',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil_genetista', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='PerfilUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_rol', models.CharField(choices=[('ADM', 'Administrador'), ('GEN', 'Genetista'), ('LEC', 'Lector/Asistente')], max_length=3)),
                ('genetista_supervisor', models.ForeignKey(blank=True, help_text='Genetista al que este Lector/Asistente está asignado (solo si el rol es Lector/Asistente).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='asistentes_asignados', to='myapp.genetistas')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil_usuario_rol', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
