# Generated by Django 5.1.6 on 2025-06-20 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='informacionpadres',
            name='identificacion',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
    ]
