# Generated by Django 5.1.6 on 2025-06-22 19:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_historiasclinicas_unique_numero_historia'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='evaluaciongenetica',
            name='check_evaluacion_proposito_or_pareja',
        ),
        migrations.RemoveConstraint(
            model_name='historiasclinicas',
            name='unique_numero_historia',
        ),
    ]
