# Generated by Django 5.1.6 on 2025-06-05 17:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_alter_autorizaciones_padre_alter_genetistas_user_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='autorizaciones',
            name='padre',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.informacionpadres', unique=True),
        ),
        migrations.AlterField(
            model_name='genetistas',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='genetistas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='PerfilUsuario',
        ),
    ]
