# Generated by Django 5.1.6 on 2025-05-30 03:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_diagnosticopresuntivo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='diagnosticopresuntivo',
            name='diagnostico',
        ),
        migrations.AlterModelOptions(
            name='diagnosticopresuntivo',
            options={'ordering': ['orden'], 'verbose_name_plural': 'Diagnósticos Presuntivos'},
        ),
        migrations.AddField(
            model_name='diagnosticopresuntivo',
            name='orden',
            field=models.PositiveIntegerField(default=0, help_text='Orden de importancia (0=primero)'),
        ),
        migrations.AlterField(
            model_name='diagnosticopresuntivo',
            name='descripcion',
            field=models.TextField(help_text='Ingrese un diagnóstico presuntivo', verbose_name='Diagnóstico Presuntivo'),
        ),
        migrations.CreateModel(
            name='EvaluacionGenetica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('signos_clinicos', models.TextField(blank=True, help_text='Describa los signos clínicos más relevantes', null=True, verbose_name='Signos Clínicos Relevantes')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('proposito', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='evaluacion_genetica', to='myapp.propositos')),
            ],
        ),
        migrations.AddField(
            model_name='diagnosticopresuntivo',
            name='evaluacion',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='diagnosticos_presuntivos', to='myapp.evaluaciongenetica'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='PlanEstudio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accion', models.TextField(help_text='Describa un paso del plan de estudio', verbose_name='Acción a realizar')),
                ('completado', models.BooleanField(default=False)),
                ('fecha_limite', models.DateField(blank=True, null=True, verbose_name='Fecha límite')),
                ('evaluacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='planes_estudio', to='myapp.evaluaciongenetica')),
            ],
            options={
                'verbose_name_plural': 'Planes de Estudio',
                'ordering': ['fecha_limite'],
            },
        ),
        migrations.DeleteModel(
            name='DiagnosticosPlanEstudio',
        ),
    ]
