# Generated by Django 5.1.6 on 2025-05-26 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_genetistas_historiasclinicas_historialcambios_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='antecedentespersonales',
            name='controles_prenatales',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
