# Generated by Django 5.1.6 on 2025-06-05 17:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_alter_autorizaciones_padre_alter_genetistas_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='genetistas',
            name='associated_genetista',
            field=models.ForeignKey(blank=True, help_text="Si el rol es Lector, genetista (con rol 'Genetista') al que está asociado.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lectores_asociados', to='myapp.genetistas'),
        ),
        migrations.AddField(
            model_name='genetistas',
            name='rol',
            field=models.CharField(choices=[('GEN', 'Genetista'), ('ADM', 'Administrador'), ('LEC', 'Lector')], default='GEN', max_length=3, verbose_name='Rol del Usuario'),
        ),
    ]
