# Generated by Django 5.1.6 on 2025-06-23 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_remove_evaluaciongenetica_check_evaluacion_proposito_or_pareja_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historiasclinicas',
            name='status',
            field=models.CharField(choices=[('borrador', 'Borrador'), ('finalizada', 'Finalizada')], default='borrador', max_length=15, verbose_name='Estado de la Historia'),
        ),
    ]
