# Generated by Django 5.1.6 on 2025-05-28 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_alter_antecedentespersonales_controles_prenatales'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='propositos',
            name='documento_nacimiento',
        ),
        migrations.AddField(
            model_name='antecedentespersonales',
            name='observaciones',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='autorizaciones',
            name='archivo_autorizacion',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='evoluciondesarrollo',
            name='resultados_examenes',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
