# Generated by Django 5.1.6 on 2025-06-03 02:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_remove_diagnosticopresuntivo_diagnostico_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='evaluaciongenetica',
            name='pareja',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.parejas'),
        ),
        migrations.AlterField(
            model_name='evaluaciongenetica',
            name='proposito',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.propositos'),
        ),
    ]
