# Generated by Django 5.1.6 on 2025-05-28 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_remove_propositos_documento_nacimiento_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='periodoneonatal',
            name='cianosis',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='periodoneonatal',
            name='convulsiones',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='periodoneonatal',
            name='hemorragia',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='periodoneonatal',
            name='ictericia',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='periodoneonatal',
            name='infecciones',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='periodoneonatal',
            name='vomitos',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
