# Generated by Django 5.1.6 on 2025-06-05 18:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_genetistas_associated_genetista_genetistas_rol'),
    ]

    operations = [
        migrations.AlterField(
            model_name='genetistas',
            name='rol',
            field=models.CharField(choices=[('ADM', 'Administrador'), ('GEN', 'Genetista'), ('LEC', 'Lector')], default='GEN', max_length=3, verbose_name='Rol del Usuario'),
        ),
        migrations.AlterField(
            model_name='historiasclinicas',
            name='genetista',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='myapp.genetistas'),
        ),
    ]
