# Generated by Django 5.1.6 on 2025-06-23 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_historiasclinicas_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historiasclinicas',
            name='status',
        ),
        migrations.AddField(
            model_name='historiasclinicas',
            name='estado',
            field=models.CharField(choices=[('borrador', 'Borrador'), ('finalizada', 'Finalizada')], default='borrador', max_length=20, verbose_name='Estado de la Historia'),
        ),
    ]
