# Generated by Django 5.1.6 on 2025-06-05 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_alter_genetistas_rol_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='genetistas',
            name='rol',
            field=models.CharField(choices=[('GEN', 'Genetista'), ('ADM', 'Administrador'), ('LEC', 'Lector')], default='GEN', max_length=3, verbose_name='Rol del Usuario'),
        ),
    ]
