# Generated by Django 5.1.6 on 2025-06-29 21:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_remove_historiasclinicas_status_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='planestudio',
            options={'ordering': ['plan_id'], 'verbose_name': 'Plan de Estudio / Consulta', 'verbose_name_plural': 'Planes de Estudio / Consultas'},
        ),
        migrations.CreateModel(
            name='ArchivoPlanEstudio',
            fields=[
                ('archivo_id', models.AutoField(primary_key=True, serialize=False)),
                ('archivo', models.FileField(upload_to='planes_estudio_archivos/', verbose_name='Archivo Adjunto')),
                ('fecha_subida', models.DateTimeField(auto_now_add=True)),
                ('plan_estudio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='archivos', to='myapp.planestudio')),
            ],
            options={
                'verbose_name': 'Archivo de Plan de Estudio',
                'verbose_name_plural': 'Archivos de Planes de Estudio',
            },
        ),
    ]
