# Generated by Django 5.1.6 on 2025-05-29 02:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_alter_periodoneonatal_cianosis_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='periodoneonatal',
            old_name='Habitos_psicologicos',
            new_name='evolucion',
        ),
    ]
