# Generated by Django 5.1.6 on 2025-06-06 01:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_alter_genetistas_rol'),
    ]

    operations = [
        migrations.AlterField(
            model_name='autorizaciones',
            name='padre',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.informacionpadres'),
        ),
        migrations.AlterField(
            model_name='autorizaciones',
            name='proposito',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.propositos'),
        ),
        migrations.AlterField(
            model_name='examenfisico',
            name='proposito',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='myapp.propositos'),
        ),
    ]
