# Generated by Django 5.1.6 on 2025-06-29 21:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_alter_planestudio_options_archivoplanestudio'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='planestudio',
            options={'ordering': ['-fecha_visita', '-plan_id'], 'verbose_name': 'Plan de Estudio / Consulta', 'verbose_name_plural': 'Planes de Estudio / Consultas'},
        ),
        migrations.DeleteModel(
            name='ArchivoPlanEstudio',
        ),
    ]
