# Generated by Django 5.1.6 on 2025-05-29 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_rename_habitos_psicologicos_periodoneonatal_evolucion'),
    ]

    operations = [
        migrations.AddField(
            model_name='periodoneonatal',
            name='observaciones_habios_psicologicos',
            field=models.TextField(blank=True, null=True),
        ),
    ]
