# Generated by Django 5.1.6 on 2025-05-29 02:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_periodoneonatal_observaciones_habios_psicologicos'),
    ]

    operations = [
        migrations.RenameField(
            model_name='periodoneonatal',
            old_name='observaciones_habios_psicologicos',
            new_name='observaciones_habitos_psicologicos',
        ),
    ]
