# Generated by Django 5.1.6 on 2025-06-06 01:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_alter_autorizaciones_padre_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='autorizaciones',
            name='padre',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.informacionpadres', unique=True),
        ),
        migrations.AlterField(
            model_name='autorizaciones',
            name='proposito',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.propositos', unique=True),
        ),
        migrations.AlterField(
            model_name='examenfisico',
            name='proposito',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.propositos', unique=True),
        ),
    ]
