# Generated by Django 5.1.6 on 2025-06-29 22:10

import django.db.models.deletion
import myapp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_alter_planestudio_options_delete_archivoplanestudio'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArchivoPlanEstudio',
            fields=[
                ('archivo_id', models.AutoField(primary_key=True, serialize=False)),
                ('archivo', models.FileField(upload_to=myapp.models.get_upload_path, verbose_name='Archivo Adjunto')),
                ('nombre_descriptivo', models.CharField(blank=True, help_text="Nombre corto para mostrar en la UI (ej: 'Ecocardiograma'). Si se deja en blanco, se usará el nombre del archivo.", max_length=150, null=True)),
                ('fecha_subida', models.DateTimeField(auto_now_add=True)),
                ('plan_estudio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='archivos', to='myapp.planestudio')),
            ],
        ),
    ]
