# Generated by Django 5.1.6 on 2025-06-06 13:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_alter_autorizaciones_padre_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='evaluaciongenetica',
            name='check_evaluacion_proposito_or_pareja',
        ),
    ]
