# Generated by Django 5.1.6 on 2025-05-29 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_rename_observaciones_habios_psicologicos_periodoneonatal_observaciones_habitos_psicologicos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='desarrollopsicomotor',
            name='caminar',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='desarrollopsicomotor',
            name='gatear',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='desarrollopsicomotor',
            name='pararse',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='desarrollopsicomotor',
            name='primeras_palabras',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='desarrollopsicomotor',
            name='primeros_dientes',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='desarrollopsicomotor',
            name='progreso_escuela',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='desarrollopsicomotor',
            name='progreso_peso',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='desarrollopsicomotor',
            name='progreso_talla',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='desarrollopsicomotor',
            name='sentarse',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='desarrollopsicomotor',
            name='sonrisa_social',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='desarrollopsicomotor',
            name='sostener_cabeza',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
