# Generated by Django 5.1.6 on 2025-05-29 13:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_alter_desarrollopsicomotor_caminar_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='diagnosticosplanestudio',
            name='diagnostico_presuntivo_1',
        ),
        migrations.RemoveField(
            model_name='diagnosticosplanestudio',
            name='diagnostico_presuntivo_2',
        ),
        migrations.RemoveField(
            model_name='diagnosticosplanestudio',
            name='diagnostico_presuntivo_3',
        ),
        migrations.CreateModel(
            name='DiagnosticoPresuntivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=255)),
                ('diagnostico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='diagnosticos_presuntivos', to='myapp.diagnosticosplanestudio')),
            ],
        ),
    ]
