# Generated by Django 5.1.6 on 2025-06-06 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_remove_evaluaciongenetica_check_evaluacion_proposito_or_pareja'),
    ]

    operations = [
        migrations.AddField(
            model_name='propositos',
            name='estado',
            field=models.CharField(choices=[('activo', 'Activo'), ('inactivo', 'Inactivo'), ('en_seguimiento', 'En Seguimiento')], default='activo', max_length=20, verbose_name='Estado del Propósito'),
        ),
    ]
