# Generated by Django 5.1.6 on 2025-05-30 00:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_remove_diagnosticosplanestudio_diagnostico_presuntivo_1_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='diagnosticopresuntivo',
            options={'ordering': ['orden']},
        ),
        migrations.RenameField(
            model_name='diagnosticopresuntivo',
            old_name='diagnostico',
            new_name='diagnostico_plan',
        ),
        migrations.RemoveField(
            model_name='diagnosticosplanestudio',
            name='diagnostico_id',
        ),
        migrations.AddField(
            model_name='diagnosticopresuntivo',
            name='orden',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='diagnosticosplanestudio',
            name='proposito',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='myapp.propositos'),
            preserve_default=False,
        ),
    ]
