# Generated by Django 5.1.6 on 2025-06-06 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_propositos_estado'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='planestudio',
            options={'ordering': ['fecha_visita'], 'verbose_name_plural': 'Planes de Estudio'},
        ),
        migrations.RemoveField(
            model_name='planestudio',
            name='fecha_limite',
        ),
        migrations.AddField(
            model_name='planestudio',
            name='asesoramiento_evoluciones',
            field=models.TextField(blank=True, null=True, verbose_name='Asesoramiento y Evoluciones'),
        ),
        migrations.AddField(
            model_name='planestudio',
            name='fecha_visita',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de Visita'),
        ),
    ]
