# Generated by Django 5.1.6 on 2025-05-30 00:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0011_alter_diagnosticopresuntivo_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='diagnosticopresuntivo',
            options={},
        ),
        migrations.RenameField(
            model_name='diagnosticopresuntivo',
            old_name='diagnostico_plan',
            new_name='diagnostico',
        ),
        migrations.RemoveField(
            model_name='diagnosticopresuntivo',
            name='orden',
        ),
        migrations.AddField(
            model_name='diagnosticosplanestudio',
            name='diagnostico_id',
            field=models.AutoField(default=1, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='diagnosticosplanestudio',
            name='proposito',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.propositos', unique=True),
        ),
    ]
