# Generated by Django 5.1.6 on 2025-06-11 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0011_alter_planestudio_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='propositos',
            name='sexo',
            field=models.CharField(blank=True, choices=[('M', 'Masculino'), ('F', 'Femenino')], max_length=1, null=True, verbose_name='Sexo'),
        ),
    ]
