# Generated by Django 5.1.6 on 2025-06-16 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0012_propositos_sexo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='diagnosticopresuntivo',
            options={'ordering': ['orden'], 'verbose_name': 'Diagnóstico Presuntivo', 'verbose_name_plural': 'Diagnósticos Presuntivos'},
        ),
        migrations.AlterModelOptions(
            name='evaluaciongenetica',
            options={'verbose_name': 'Evaluación Genética', 'verbose_name_plural': 'Evaluaciones Genéticas'},
        ),
        migrations.AlterModelOptions(
            name='planestudio',
            options={'ordering': ['-fecha_visita', '-plan_id'], 'verbose_name': 'Plan de Estudio / Consulta', 'verbose_name_plural': 'Planes de Estudio / Consultas'},
        ),
        migrations.AlterField(
            model_name='diagnosticopresuntivo',
            name='orden',
            field=models.PositiveIntegerField(default=0, help_text='Orden de importancia (0=más probable, 1=segundo, etc.)'),
        ),
        migrations.AlterField(
            model_name='evaluaciongenetica',
            name='signos_clinicos',
            field=models.TextField(blank=True, help_text='Describa los signos clínicos más relevantes que inician esta evaluación.', null=True, verbose_name='Signos Clínicos Relevantes'),
        ),
        migrations.AlterField(
            model_name='planestudio',
            name='accion',
            field=models.TextField(help_text='Describa el plan de estudio, exámenes o pasos a seguir para la próxima consulta.', verbose_name='Acción a realizar / Exámenes solicitados'),
        ),
        migrations.AlterField(
            model_name='planestudio',
            name='asesoramiento_evoluciones',
            field=models.TextField(blank=True, help_text='Llenar este campo cuando el paciente regrese y el plan se marque como completado.', null=True, verbose_name='Asesoramiento y Evoluciones (Resultados de la consulta)'),
        ),
        migrations.AlterField(
            model_name='planestudio',
            name='completado',
            field=models.BooleanField(default=False, verbose_name='Plan Completado'),
        ),
        migrations.AlterField(
            model_name='planestudio',
            name='fecha_visita',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de Próxima Visita / Límite'),
        ),
        migrations.AddConstraint(
            model_name='evaluaciongenetica',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('pareja__isnull', True), ('proposito__isnull', False)), models.Q(('pareja__isnull', False), ('proposito__isnull', True)), _connector='OR'), name='check_evaluacion_proposito_or_pareja'),
        ),
    ]
